version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: voice-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voice-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    command: ["bash", "-lc", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voice-frontend
    environment:
      - BACKEND_ORIGIN=http://backend:8000
      - N8N_ORIGIN=http://n8n:5678
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - n8n
    volumes:
      - ./frontend:/app
    command: ["sh", "-lc", "npm install && npm run dev -- -p 3000 -H 0.0.0.0"]

  n8n:
    image: n8nio/n8n:latest
    container_name: voice-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - WEBHOOK_URL=http://localhost:5678
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - ollama

volumes: {}


